dist: xenial
language: java
jdk: openjdk14
cache:
  directories:
  - "$HOME/.m2/repository"
env:
- CLI_VERSION=latest
before_script:
- 'curl -H ''Cache-Control: no-cache'' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh
  | sudo bash'
script:
- mvn clean install
- fossa init
- fossa analyze
deploy:
  - provider: bintray
    file: bintray_info_maven.JSON
    user: incplusplus
    key: "$bintray_key"
    skip_cleanup: true
    on:
      repo: IncPlusPlus/bigtoolbox-parent
      branch: master
  - provider: releases
    api_key:
      secure: FbbLtVhw9zVsfn4qKiGL3jGK5XifH57EM9s4HYR0Rorfk3CKeCrKT6l7+fvCyEKWFonkBcYbnpxdLEYyLQW1zLPrSbZ7XS62d49+QZGV7s/ERllmYSe6ceIdwd5wfXFtRN/Six6DVxyJu0qtGAXnDgoH+V8bwnNh+q9dwOrX5sNGr/MEREroblHWjV+iiP2uBRRRvXPahFRGwDZfiSz8ZmeDofbdHa7klDdb8qxPuu6HuOsJMOeuN64U+vMyNRbjSqWqSyIQGivsBvZWLJZWAZHCULCA908ozgpZN4GXO5FpACqePLWB+sDP2GdP2UxJF5k6asI5JlureoFDR/PzrdkZbYoE7I4BN5lLhjKNp240jp/XESLXjPBZUFhJNwNOX3ACBK44c3GWXFfGsdbBFeiwiwWU9TSLo9wK51gm/vHDTyYLxtDwBX3htGpAGyit/+cIlpB4nonRNIlN07yXZun+GAJ8rZJ740HG55131uTmh3yYuIHjGIgaKvwHottPAFRcK9q7zebrO4gOvgtG/vr0xJ3Ts2its8IJSSxJSGMvFG8aXcxQH+Opr/GUh0yu3lLlJobCwr7hsuhDsTivl0H/v3xK4CpPiLOMDEFb1vOPZA5jCjeDG6Bl2QQFgzQr+i7cSr1ZNYbj8KnMqsIwZ4CsrM7FYzTCMEeXwTTgfOE=
    file_glob: true
    file: target/bigtoolbox-parent-*.*.*.pom
    skip_cleanup: true
    prerelease: true
    on:
      repo: IncPlusPlus/bigtoolbox-parent
      branch: master
      tags: true